name: Siose
version: 1.0
main: me.samarthh.Main
api-version: 1.20

commands:
  getdata:
    description: Fetches data from an API (requires authentication)
    usage: /<command>
  register:
    description: Register for authentication
    usage: /<command>
  login:
    description: Login with your token
    usage: /<command> <token>
  logout:
    description: Logout and clear authentication
    usage: /<command>